---
- name: Ensure tracking directory exists
  file:
    path: /var/lib/devops-framework/images
    state: directory
    mode: '0755'

- name: Get current healthy image info (if exists)
  slurp:
    src: "/var/lib/devops-framework/images/{{ lookup('env', 'ENV') }}_{{ lookup('env', 'VERSION') }}_healthy.json"
  register: current_healthy_image
  ignore_errors: yes
  changed_when: false

- name: Parse current healthy image
  set_fact:
    previous_healthy_images: "{{ (current_healthy_image.content | b64decode | from_json).images | default([]) }}"
  when: current_healthy_image is succeeded
  ignore_errors: yes

- name: Extract new images from docker run commands
  set_fact:
    new_deployed_images: []

- name: Build list of newly deployed images
  set_fact:
    new_deployed_images: "{{ new_deployed_images + [{'name': item.split() | last, 'timestamp': ansible_date_time.iso8601}] }}"
  loop: "{{ hostvars[inventory_hostname].get('docker_run_commands', []) }}"
  when: hostvars[inventory_hostname].get('docker_run_commands', []) | length > 0
  loop_control:
    label: "{{ item.split() | last }}"

- name: Display tracking information
  debug:
    msg: |
      Previous healthy images: {{ previous_healthy_images | default([]) | length }}
      New deployed images: {{ new_deployed_images | length }}
  when: not global_no_log
