---
- name: Create image tracking file
  copy:
    content: |
      {
        "env": "{{ env }}",
        "project_id": "{{ project_id }}",
        "branch_name": "{{ sanitized_branch_name }}",
        "version": "{{ version }}",
        "timestamp": "{{ ansible_date_time.iso8601 }}",
        "images": {{ new_deployed_images | to_nice_json }}
      }
    dest: "/var/lib/dockflow/images/{{ env }}_{{ project_id }}_{{ sanitized_branch_name }}_{{ version }}.json"
    mode: '0644'

- name: Log successful deployment
  debug:
    msg: "Marked {{ new_deployed_images | length }} images as healthy for {{ env }}/{{ version }}"
