---
- name: Deploy Docker Images to Remote Server
  hosts: all:!localhost
  vars:    
    compose_path: "{{ lookup('env', 'PROJECT_ROOT') }}/.deployment/docker/docker-compose.yml"
    tmp_dir: "/tmp"
    global_no_log: "{{ not (lookup('env', 'FRAMEWORK_OPTIONS_ENABLE_DEBUG_LOGS') | default('false') | bool) }}"
    deploy_services: "{{ lookup('env', 'DEPLOY_DOCKER_SERVICES') | default('', true) }}"
    services_option: "{{ '--services=' + deploy_services if deploy_services else '' }}"
    environmentize_option: "{{ '--environmentize' if ((lookup('env', 'FRAMEWORK_OPTIONS_ENVIRONMENTIZE') | default('true', true)) | bool) else '' }}"
    remote_build: "{{ (lookup('env', 'FRAMEWORK_OPTIONS_REMOTE_BUILD') | default('false', true)) | bool }}"
    framework_version: "1.0.38-dev1"
    decomposerize_types:
      - name: "setup"
        base_options: "--create-networks --create-volumes --stop-and-remove"
        ignore_errors: yes  # Networks/volumes might already exist
      - name: "run"
        base_options: "--docker-run --docker-run-detach"
        ignore_errors: no
      - name: "cleanup"
        base_options: "--delete-images"
        ignore_errors: yes  # Will be skipped if rollback is configured
        skip_on_rollback: yes
  pre_tasks:
    - name: Display DevOps Framework version
      debug:
        msg: "DevOps Framework v{{ framework_version }}"
    
    - name: Ensure rollback directory exists
      file:
        path: /var/lib/devops-framework
        state: directory
        mode: '0755'
    
    - name: Check if config.yml exists
      stat:
        path: "{{ lookup('env', 'PROJECT_ROOT') }}/.deployment/config.yml"
      delegate_to: localhost
      register: config_file
      changed_when: false

    - name: Render config.yml template with evaluated variables
      template:
        src: "{{ lookup('env', 'PROJECT_ROOT') }}/.deployment/config.yml"
        dest: "{{ tmp_dir }}/config_rendered.yml"
      delegate_to: localhost
      when: config_file.stat.exists
      changed_when: false

    - name: Load deployment configuration from rendered template
      include_vars:
        file: "{{ tmp_dir }}/config_rendered.yml"
        name: deployment_config
      when: config_file.stat.exists
      ignore_errors: yes
  roles:
    - role: geerlingguy.docker
    - role: nginx
      tags:
        - nginx
    - role: private_ssh_keys
    - role: services   
    - role: remote-build
      when: remote_build | bool
    - role: image-transfer
      when: not (remote_build | bool)
    - role: execute-scripts
  tasks:
    - name: Check if rollback is configured
      set_fact:
        rollback_configured: "{{ (deployment_config.health_checks.on_failure | default('notify')) == 'rollback' }}"
      when: deployment_config is defined and deployment_config.health_checks is defined

    - name: Process Docker commands for each type (with logs)
      include_tasks: process_docker_commands.yml
      loop: "{{ decomposerize_types }}"
      loop_control:
        loop_var: cmd_type
      no_log: false
      when:
        - not global_no_log
        - not (cmd_type.skip_on_rollback | default(false) and rollback_configured | default(false))

    - name: Process Docker commands for each type (silent)
      include_tasks: process_docker_commands.yml
      loop: "{{ decomposerize_types }}"
      loop_control:
        loop_var: cmd_type
      no_log: true
      when:
        - global_no_log
        - not (cmd_type.skip_on_rollback | default(false) and rollback_configured | default(false))

  post_tasks:
    - name: Set health checks configuration
      set_fact:
        health_checks_config: "{{ deployment_config.health_checks | default({}) }}"
      when: deployment_config is defined

    - name: Run health checks
      include_role:
        name: health-check
      when: health_checks_config is defined or (deployment_config.health_checks is defined)