name: Build

on:
  workflow_call:
    inputs:
      free-disk-space:
        required: false
        type: boolean
        default: false
        description: "Free disk space by removing unnecessary tools"

env:
  DOCKFLOW_REPOSITORY_URL: https://github.com/Shawiizz/dockflow.git
  DOCKFLOW_FRAMEWORK_VERSION: 1.0.38-dev24

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build Docker images

    steps:
      - name: Free Disk Space (Ubuntu)
        if: ${{ inputs.free-disk-space }}
        uses: jlumbroso/free-disk-space@main
        with:
          docker-images: false

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install docker-decompose
        run: npm i -g shawiizz-decomposerize

      - name: Clone dockflow repository
        run: git clone --branch "$DOCKFLOW_FRAMEWORK_VERSION" "$DOCKFLOW_REPOSITORY_URL" dockflow

      - name: Build Docker images
        run: |
          export ENV=build
          export VERSION=build
          bash dockflow/.github/scripts/build_docker_images.sh
