name: Deploy

on:
  workflow_call:
    inputs:
      tag:
        required: false
        type: string
        description: "The tag to deploy, e.g. 1.0.0 or 1.0.0-staging"
      version:
        required: false
        type: string
        description: "The version to deploy, e.g. 1.0.0"
      free-disk-space:
        required: false
        type: boolean
        default: false
        description: "Free disk space by removing unnecessary tools"

env:
  DEVOPS_REPOSITORY_URL: https://github.com/Shawiizz/devops-framework.git
  DEVOPS_FRAMEWORK_VERSION: 1.0.38-dev1

jobs:
  discover-hosts:
    runs-on: ubuntu-latest
    name: Discover deployment hosts
    outputs:
      hosts: ${{ steps.discover.outputs.hosts }}
      env: ${{ steps.discover.outputs.env }}
      tag: ${{ steps.discover.outputs.tag }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Discover hosts and environment
        id: discover
        run: |
          if [ -n "${{ inputs.tag }}" ]; then
            TAG="${{ inputs.tag }}"
            ENVIRONMENT="production"
            
            if [[ "$TAG" == *"-"* ]]; then
              ENVIRONMENT="${TAG##*-}"
            fi
          elif [ -n "${{ inputs.version }}" ]; then
            TAG="${{ inputs.version }}"
            ENVIRONMENT="production"
          else
            echo "::error:: Either tag or version input must be provided"
            exit 1
          fi

          echo "env=$ENVIRONMENT" >> $GITHUB_OUTPUT
          echo "tag=$TAG" >> $GITHUB_OUTPUT
          
          #######################################
          ###### Discover hosts to deploy #######
          #######################################
          HOSTS_LIST=()
          BASE_FILE=".deployment/env/.env.${ENVIRONMENT}"
          
          # Check if main env file exists
          if [ -f "$BASE_FILE" ]; then
            HOSTS_LIST+=("main")
          fi
          
          # Check for host-specific env files
          for env_file in .deployment/env/.env.${ENVIRONMENT}.*; do
            if [ -f "$env_file" ]; then
              SUFFIX=$(basename "$env_file" | sed "s/\.env\.${ENVIRONMENT}\.//")
              if [[ "$SUFFIX" != "${ENVIRONMENT}" ]]; then
                HOSTS_LIST+=("$SUFFIX")
              fi
            fi
          done
          
          # If no env files found, deploy to main host using CI secrets only
          if [ ${#HOSTS_LIST[@]} -eq 0 ]; then
            echo "No .env files found for environment ${ENVIRONMENT}, will use CI secrets only"
            HOSTS_LIST+=("main")
          fi
          
          HOSTS_JSON="["
          for i in "${!HOSTS_LIST[@]}"; do
            if [ $i -eq 0 ]; then
              HOSTS_JSON="$HOSTS_JSON\"${HOSTS_LIST[$i]}\""
            else
              HOSTS_JSON="$HOSTS_JSON,\"${HOSTS_LIST[$i]}\""
            fi
          done
          HOSTS_JSON="$HOSTS_JSON]"
          
          echo "hosts=$HOSTS_JSON" >> $GITHUB_OUTPUT
          echo "Discovered hosts: $HOSTS_JSON"

  deploy:
    runs-on: ubuntu-latest
    name: Deploy to ${{ needs.discover-hosts.outputs.env }} (${{ matrix.host }} host)
    needs: discover-hosts
    strategy:
      matrix:
        host: ${{ fromJson(needs.discover-hosts.outputs.hosts) }}
    steps:
      - name: Free Disk Space (Ubuntu)
        if: ${{ inputs.free-disk-space }}
        uses: jlumbroso/free-disk-space@main
        with:
          docker-images: false

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup environment variables for host ${{ matrix.host }}
        id: vars
        run: |
          ENV="${{ needs.discover-hosts.outputs.env }}"
          HOST="${{ matrix.host }}"

          echo "env=$ENV" >> $GITHUB_OUTPUT
          echo "host=$HOST" >> $GITHUB_OUTPUT
          echo "tag=${{ needs.discover-hosts.outputs.tag }}" >> $GITHUB_OUTPUT

      - name: Install dependencies
        run: |
          npm i -g shawiizz-decomposerize
          wget https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 -O /usr/local/bin/yq &&\
          chmod +x /usr/local/bin/yq

      - name: Clone devops repository
        run: git clone --branch "$DEVOPS_FRAMEWORK_VERSION" "$DEVOPS_REPOSITORY_URL" devops-framework

      - name: Deploy to host ${{ matrix.host }}
        run: |          
          # Load secrets as environment variables
          echo '${{ toJSON(secrets) }}' > secrets.json
          for key in $(jq -r 'keys[]' secrets.json); do
            value=$(jq -r --arg key "$key" '.[$key]' secrets.json)
            export "$key=$value"
          done

          ENV="${{ steps.vars.outputs.env }}"
          export HOSTNAME="${{ steps.vars.outputs.host }}"
          
          #######################################
          ######### Load env variables ##########
          #######################################
          set -a
          if [ -f ".deployment/env/.env.${ENV}" ]; then
            echo "Loading .deployment/env/.env.${ENV}"
            source ".deployment/env/.env.${ENV}"
          else
            echo "No .deployment/env/.env.${ENV} file found, using CI secrets only"
          fi
          
          if [[ "$HOSTNAME" != "main" ]]; then
            if [ -f ".deployment/env/.env.${ENV}.${HOSTNAME}" ]; then
              echo "Loading .deployment/env/.env.${ENV}.${HOSTNAME}"
              source ".deployment/env/.env.${ENV}.${HOSTNAME}"
            fi
          fi
          set +a
          
          # Override variables from CI secrets if defined
          ENV_PREFIX="$(echo "${ENV}" | tr '[:lower:]' '[:upper:]')_"
          
          if [[ "$HOSTNAME" == "main" ]]; then
            # Main host: process ENV_* variables
            echo "Processing CI secrets with prefix: ${ENV_PREFIX}"
            for var in $(compgen -e); do
              if [[ "$var" == ${ENV_PREFIX}* ]]; then
                # Remove ENV_ prefix
                var_name="${var#${ENV_PREFIX}}"
                var_value="${!var}"
                export "$var_name=$var_value"
                echo "Exported $var_name from CI secret $var"
              fi
            done
          else
            # Specific host: process ENV_HOSTNAME_* variables
            ENV_HOSTNAME_PREFIX="${ENV_PREFIX}$(echo "${HOSTNAME}" | tr '[:lower:]' '[:upper:]')_"
            echo "Processing CI secrets with prefix: ${ENV_HOSTNAME_PREFIX}"
            for var in $(compgen -e); do
              if [[ "$var" == ${ENV_HOSTNAME_PREFIX}* ]]; then
                # Remove ENV_HOSTNAME_ prefix
                var_name="${var#${ENV_HOSTNAME_PREFIX}}"
                var_value="${!var}"
                export "$var_name=$var_value"
                echo "Exported $var_name from CI secret $var"
              fi
            done
          fi
          
          # Set default USER if not already set
          if [ -z "$USER" ]; then
            export USER="deploy"
          fi
          
          # Verify that HOST is defined
          if [ -z "$HOST" ]; then
            echo "::error:: HOST is not defined. Please set it in .env file or as CI secret (${ENV_PREFIX}HOST)"
            exit 1
          fi
          
          # Verify that SSH_PRIVATE_KEY is defined
          if [ -z "$SSH_PRIVATE_KEY" ]; then
            echo "::error:: SSH_PRIVATE_KEY is not defined. Please set it as CI secret (${ENV_PREFIX}SSH_PRIVATE_KEY)"
            exit 1
          fi
                              
          export ENV="${{ steps.vars.outputs.env }}"
          export VERSION="${{ steps.vars.outputs.tag }}"

          #######################################
          ### Load framework config options #####
          #######################################
          if [ -f ".deployment/config.yml" ]; then
            echo "Loading framework configuration options from .deployment/config.yml"
            export $(yq e '.options | to_entries | map("FRAMEWORK_OPTIONS_" + .key + "=" + .value) | join(" ")' .deployment/config.yml | awk -F= '{printf "%s=%s ", toupper($1), $2}')
          else
            echo "No .deployment/config.yml found, skipping framework configuration options"
          fi

          #######################################
          ######### Build docker images #########
          #######################################
          if [[ "${FRAMEWORK_OPTIONS_REMOTE_BUILD}" != "true" ]]; then
            echo "Building Docker images locally in CI/CD..."
            if [[ "$HOSTNAME" == "main" ]]; then
              bash devops-framework/.github/scripts/build_docker_images.sh
            else
              bash devops-framework/.github/scripts/build_docker_images.sh --host="$HOSTNAME"
            fi
          else
            echo "Remote build enabled - skipping local image build"
            echo "Images will be built directly on the remote server"
          fi

          #######################################
          ######### Save project root path ######
          #######################################
          export PROJECT_ROOT=$(pwd)

          ######### Change working directory #########
          cd devops-framework
          
          #######################################
          ############ Setup SSH Key ############
          #######################################
          
          mkdir -p ssh
          echo "$SSH_PRIVATE_KEY" | tr -d '\r' > ssh/remote_private_key
          chmod 600 ssh/*
          eval "$(ssh-agent -s)"
          ssh-add ssh/remote_private_key

          #######################################
          ######### Deploy with Ansible #########
          #######################################
          export ANSIBLE_HOST_KEY_CHECKING=False
          export USER_PASSWORD=${{ secrets.USER_PASSWORD }}
          export GIT_TOKEN=${{ secrets.GIT_TOKEN }}

          SKIP_TAGS="configure_host"
          if [ ! -d "../.deployment/templates/nginx" ] || [ -z "$(ls -A ../.deployment/templates/nginx 2>/dev/null)" ]; then
            echo "No nginx configuration found, skipping nginx role"
            SKIP_TAGS="${SKIP_TAGS},nginx"
          fi
          
          if [[ "$HOSTNAME" == "main" ]]; then
            INVENTORY_HOST="${ENV}"
          else
            INVENTORY_HOST="${ENV}-${HOSTNAME}"
          fi
          
          sed -i "s/REMOTE_HOST/${INVENTORY_HOST}/g" ansible/inventory.yml
          ansible-galaxy role install geerlingguy.docker
          ansible-playbook ansible/deploy.yml -i ansible/inventory.yml --skip-tags "$SKIP_TAGS"
