name: Deploy

on:
  workflow_call:
    inputs:
      tag:
        required: false
        type: string
        description: "The tag to deploy, e.g. 1.0.0 or 1.0.0-staging"
      version:
        required: false
        type: string
        description: "The version to deploy, e.g. 1.0.0"
      free-disk-space:
        required: false
        type: boolean
        default: false
        description: "Free disk space by removing unnecessary tools"

env:
  DOCKFLOW_REPOSITORY_URL: https://github.com/Shawiizz/dockflow.git
  DOCKFLOW_FRAMEWORK_VERSION: 1.0.40-dev2

jobs:
  discover-hosts:
    runs-on: ubuntu-latest
    name: Discover deployment hosts
    outputs:
      hosts: ${{ steps.discover.outputs.hosts }}
      env: ${{ steps.discover.outputs.env }}
      tag: ${{ steps.discover.outputs.tag }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Discover hosts and environment
        id: discover
        run: |
          if [ -n "${{ inputs.tag }}" ]; then
            TAG="${{ inputs.tag }}"
            ENVIRONMENT="production"
            
            if [[ "$TAG" == *"-"* ]]; then
              ENVIRONMENT="${TAG##*-}"
            fi
          elif [ -n "${{ inputs.version }}" ]; then
            TAG="${{ inputs.version }}"
            ENVIRONMENT="production"
          else
            echo "::error:: Either tag or version input must be provided"
            exit 1
          fi

          echo "env=$ENVIRONMENT" >> $GITHUB_OUTPUT
          echo "tag=$TAG" >> $GITHUB_OUTPUT
          
          # Clone dockflow framework to access discovery script
          git clone --depth 1 --branch "${{ env.DOCKFLOW_FRAMEWORK_VERSION }}" "${{ env.DOCKFLOW_REPOSITORY_URL }}" /tmp/dockflow
          
          # Make scripts executable
          chmod +x /tmp/dockflow/.github/scripts/*.sh
          
          # Discover hosts
          HOSTS_JSON=$(/tmp/dockflow/.github/scripts/discover_hosts.sh "$ENVIRONMENT")
          echo "hosts=$HOSTS_JSON" >> $GITHUB_OUTPUT
          echo "Discovered hosts: $HOSTS_JSON"

  deploy:
    runs-on: ubuntu-latest
    name: Deploy to ${{ needs.discover-hosts.outputs.env }} (${{ matrix.host }} host)
    needs: discover-hosts
    strategy:
      matrix:
        host: ${{ fromJson(needs.discover-hosts.outputs.hosts) }}
    steps:
      - name: Free Disk Space (Ubuntu)
        if: ${{ inputs.free-disk-space }}
        uses: jlumbroso/free-disk-space@main
        with:
          docker-images: false

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup environment variables for host ${{ matrix.host }}
        id: vars
        run: |
          ENV="${{ needs.discover-hosts.outputs.env }}"
          HOST="${{ matrix.host }}"

          echo "env=$ENV" >> $GITHUB_OUTPUT
          echo "host=$HOST" >> $GITHUB_OUTPUT
          echo "tag=${{ needs.discover-hosts.outputs.tag }}" >> $GITHUB_OUTPUT

      - name: Install dependencies
        run: |
          npm i -g shawiizz-decomposerize
          wget https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 -O /usr/local/bin/yq &&\
          chmod +x /usr/local/bin/yq

      - name: Clone dockflow repository
        run: git clone --branch "$DOCKFLOW_FRAMEWORK_VERSION" "$DOCKFLOW_REPOSITORY_URL" dockflow

      - name: Deploy to host ${{ matrix.host }}
        run: |          
          # Load secrets as environment variables
          echo '${{ toJSON(secrets) }}' > secrets.json
          for key in $(jq -r 'keys[]' secrets.json); do
            value=$(jq -r --arg key "$key" '.[$key]' secrets.json)
            export "$key=$value"
          done

          ENV="${{ steps.vars.outputs.env }}"
          export HOSTNAME="${{ steps.vars.outputs.host }}"
          
          # Load environment variables using helper script
          source dockflow/.github/scripts/load_env.sh "$ENV" "$HOSTNAME"
                              
          export ENV="${{ steps.vars.outputs.env }}"
          export VERSION="${{ steps.vars.outputs.tag }}"

          #######################################
          ### Load framework config options #####
          #######################################
          if [ -f ".deployment/config.yml" ]; then
            echo "Loading framework configuration options from .deployment/config.yml"
            export $(yq e '.options | to_entries | map("FRAMEWORK_OPTIONS_" + .key + "=" + .value) | join(" ")' .deployment/config.yml | awk -F= '{printf "%s=%s ", toupper($1), $2}')
          else
            echo "No .deployment/config.yml found, skipping framework configuration options"
          fi

          #######################################
          ######### Build docker images #########
          #######################################
          if [[ "${FRAMEWORK_OPTIONS_REMOTE_BUILD}" != "true" ]]; then
            echo "Building Docker images locally in CI/CD..."
            if [[ "$HOSTNAME" == "main" ]]; then
              bash dockflow/.github/scripts/build_docker_images.sh
            else
              bash dockflow/.github/scripts/build_docker_images.sh --host="$HOSTNAME"
            fi
          else
            echo "Remote build enabled - skipping local image build"
            echo "Images will be built directly on the remote server"
          fi

          #######################################
          ######### Save project root path ######
          #######################################
          export ROOT_PATH=$(pwd)

          ######### Change working directory #########
          cd dockflow
          
          #######################################
          ############ Setup SSH Key ############
          #######################################
          
          mkdir -p ssh
          echo "$SSH_PRIVATE_KEY" | tr -d '\r' > ssh/remote_private_key
          chmod 600 ssh/*
          eval "$(ssh-agent -s)"
          ssh-add ssh/remote_private_key

          #######################################
          ######### Deploy with Ansible #########
          #######################################
          export ANSIBLE_HOST_KEY_CHECKING=False
          export USER_PASSWORD=${{ secrets.USER_PASSWORD }}
          export GIT_TOKEN=${{ secrets.GIT_TOKEN }}
          export PROJECT_ID="${{ github.repository_id }}"
          
          # Get original branch name instead of tag name
          if [[ "${{ github.ref_type }}" == "tag" ]]; then
            ORIGINAL_BRANCH=$(git branch -r --contains ${{ github.ref_name }} | grep -v "HEAD" | head -n1 | sed 's/.*origin\///')
            if [ -n "$ORIGINAL_BRANCH" ]; then
              export BRANCH_NAME=$ORIGINAL_BRANCH
            else
              export BRANCH_NAME=$(git remote show origin | grep "HEAD branch" | cut -d ":" -f 2 | xargs)
            fi
          else
            export BRANCH_NAME=${{ github.ref_name }}
          fi

          # Export all environment variables to YAML file for Ansible
          python3 << 'PYTHON_EOF'
          import os
          import yaml

          env_vars = {}
          for key, value in os.environ.items():
              if key and key not in ['_', 'OLDPWD']:
                  # Convert to lowercase for consistency
                  key_lower = key.lower()
                  env_vars[key_lower] = value

          # Write as proper YAML with multiline support
          with open('/tmp/ansible_env_vars.yml', 'w') as f:
              yaml.dump(env_vars, f, default_flow_style=False, allow_unicode=True)
          PYTHON_EOF

          SKIP_TAGS="configure_host"
          if [ ! -d "../.deployment/templates/nginx" ] || [ -z "$(ls -A ../.deployment/templates/nginx 2>/dev/null)" ]; then
            echo "No nginx configuration found, skipping nginx role"
            SKIP_TAGS="${SKIP_TAGS},nginx"
          fi
          
          INVENTORY_HOST="${ENV}$([[ "$HOSTNAME" != "main" ]] && echo "-${HOSTNAME}" || echo "")"
          
          sed -i "s/REMOTE_HOST/${INVENTORY_HOST}/g" ansible/inventory.yml
          ansible-galaxy role install geerlingguy.docker
          ansible-playbook ansible/deploy.yml -i ansible/inventory.yml --skip-tags "$SKIP_TAGS"
